### ISSUE TITLE
bash doesn't support /dev/tcp/host/port

### ISSUE THREAD

**Issue by phuongnd08** [coreos/coreos-overlay#1032]
On a CentOS server, I can see bash 4.1.2 (released 2009) handle /dev/tcp/host/port just fine.
On lastest stable CoreOS 540.0.0 bash do not understand /dev/tcp/host/port, which is a bit weird because this is running bash 4.2.50 (released 2011). Any reason for that? Any chance it get supported?

**Comment by marineam** [comment]
This feature was intentionally disabled to reduce the number of ways bash may surprise us security-wise in the future. For networking in shell scripts I would recommend using `ncat`, the netcat variant we ship in CoreOS.
