### ISSUE TITLE
Parse space-separated value of environment variables in docker.service

### ISSUE THREAD

**Issue by budnyjj** [coreos/coreos-overlay#1052]
Hello!
I'm trying to pass two additional command line arguments to docker service by cloud-init:

```bash
write_files:
  - path: /etc/systemd/system/docker.service.d/50-dns-params.conf
    content: |
       [Service]
       Environment=DOCKER_OPTS='--bip="172.17.42.1/16" --dns="172.17.42.1"'
```

However, this don't work correctly:

```bash
systemctl status docker
...
/usr/bin/docker --daemon --storage-driver=btrfs --host=fd:// --bip=172.17.42.1/16
```

As you can see, systemd substitites only first part of overriden variable.
From systemd.service(5):
"Basic environment variable substitution is supported. Use "${FOO}" as part of a word, or as a word of its own, on  the command line, in which case it will be replaced by the value of the environment variable including all whitespace it contains, resulting in a single argument. Use "$FOO" as a separate word on the command line, in which case it will be replaced by the value of the environment variable split at whitespace, resulting in zero or more arguments."

So, I propose you to modify app-emulation/docker/files/docker-service:
from 
```bash 
ExecStart=/usr/bin/docker --daemon --host=fd:// $DOCKER_OPTS
```

to
```bash
ExecStart=/usr/bin/docker --daemon --host=fd:// ${DOCKER_OPTS}
```

**Comment by crawford** [comment]
When I tested the drop-in:
```
[Service]
Environment=DOCKER_OPTS='--bip="172.17.42.1/16" --dns="172.17.42.1"'
```

I got `Invalid environment assignment, ignoring: DOCKER_OPTS='--bip="172.17.42.1/16" --dns="172.17.42.1"'`, which resulted in only `--bip="172.17.42.1/16"` being populated.

What you actually want is:
```
[Service]
Environment='DOCKER_OPTS=--bip="172.17.42.1/16" --dns="172.17.42.1"'
```

(extremely subtle placement of the opening single-quote).

**Comment by budnyjj** [comment]
It works.
Thank you!
