### ISSUE TITLE
Support for SMB 2.1??

### ISSUE THREAD

**Issue by StephenOTT** [coreos/coreos-overlay#1064]
We are looking at this:
http://blog.elastocloud.org/2014/06/using-azure-file-service-on-linux.html

We are seeing that CoreOS currently does not appear to support SMB2.1

How can we get SMB2.1 support?

```
core@coreos-1 /tmp $ zcat /proc/config.gz | grep CONFIG_CIFS
CONFIG_CIFS=m
CONFIG_CIFS_STATS=y
CONFIG_CIFS_STATS2=y
CONFIG_CIFS_WEAK_PW_HASH=y
CONFIG_CIFS_UPCALL=y
CONFIG_CIFS_XATTR=y
CONFIG_CIFS_POSIX=y
CONFIG_CIFS_ACL=y
CONFIG_CIFS_DEBUG=y
# CONFIG_CIFS_DEBUG2 is not set
CONFIG_CIFS_DFS_UPCALL=y
# CONFIG_CIFS_SMB2 is not set
```

@sylus

**Comment by StephenOTT** [comment]
@chanezzon

**Comment by StephenOTT** [comment]
@chanezon

**Comment by sylus** [comment]
:+1:

**Comment by philips** [comment]
I see no reason not to enable this. /cc @gregkh @marineam

**Comment by StephenOTT** [comment]
This is a major blocker for us at the moment because Azure File Service does not support smb1.x

**Comment by gregkh** [comment]
Looks like a good idea to me.

**Comment by StephenOTT** [comment]
Hey guys

Any potential timeline on this being added?

**Comment by crawford** [comment]
......did not close this GitHub.

**Comment by crawford** [comment]
@StephenOTT it will be present in the next release after 575.0.0 (should be released within a couple of days).

**Comment by StephenOTT** [comment]
Thanks!!  Amazing.  Will really help us out!

**Comment by crawford** [comment]
This is now in Alpha 584.0.0.

**Comment by sylus** [comment]
Thanks so much you guys are awesome!

**Comment by IbnSaeed** [comment]
Thanks
