### ISSUE TITLE
Add `jq` 

### ISSUE THREAD

**Issue by brendanjerwin** [coreos/coreos-overlay#1116]
jq - http://stedolan.github.io/jq/

Seems really lightweight, no dependencies.

Would really make it easier to write health checks / discovery / registration services.

**Comment by jumanjiman** [comment]
@brendanjerwin instead of including jq on coreos, how about:

```console
core@ip-192-168-254-162 ~/jq $ cat Dockerfile 
FROM alpine:latest
RUN apk add -U jq && rm -f /var/cache/apk/*
ENTRYPOINT ["jq"]


core@ip-192-168-254-162 ~/jq $ docker images | grep jq
jq                                    latest              64c89bc7efe2        44 seconds ago      5.451 MB


core@ip-192-168-254-162 ~/jq $ alias jq="docker run --rm -it -v /tmp:/tmp jq"


core@ip-192-168-254-162 ~/jq $ jq --help

jq - commandline JSON processor [version 1.4]
Usage: jq [options] <jq filter> [file...]

For a description of the command line options and
how to write jq filters (and why you might want to)
see the jq manpage, or the online documentation at
http://stedolan.github.com/jq
```

**Comment by PierreKircher** [comment]
- name: jqservice.service
    content: |
      [Unit]
      Description=jqservice

      [Service]
      ExecStartPre=/usr/bin/curl -sSL -o /opt/bin/jq http://stedolan.github.io/jq/download/linux64/jq
      ExecStar=/usr/bin/chmod +x /opt/bin/jq

**Comment by brendanjerwin** [comment]
OK, yeah, _that_ I could be down with @PierreKircher. Duh.

**Comment by pwaller** [comment]
FWIW, I'd love to see this shipped with CoreOS too, since JSON is the blood in the veins of the cloud.

**Comment by marineam** [comment]
jq has been added:
https://github.com/coreos/coreos-overlay/pull/1291
https://coreos.com/releases/#717.0.0
