### ISSUE TITLE
Enhanced SR-IOV support: ixgbevf module > 2.14.2 ?

### ISSUE THREAD

**Issue by ianblenke** [coreos/coreos-overlay#1148]
The AWS EC2 User Guide for Enhanced Networking references an ixgbevf module version greater than 2.14.2.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

CoreOS seems to be shipping with 2.12.1-k, which appears to have been last updated on 2013-12-20 (http://sourceforge.net/projects/e1000/files/ixgbevf%20stable/2.12.1/)

It looks like there are some gentoo overlays out there that support newer versions of ixgbevf.

**Comment by ryansch** [comment]
I just bumped my head on this as well.

**Comment by skippy** [comment]
+1

**Comment by jumanjiman** [comment]
:+1: 

bumped into this recently, too

**Comment by marineam** [comment]
The driver is from mainline Linux where it is continuously maintained as part of the normal development cycle. So the driver is certainly *not* the old `2.12.1-k` release even though that string hasn't been changed. How far it differs from `2.14.2` I have no idea but Intel is directly involved in maintaining the driver in mainline so I would be surprised if the differences are significant. I haven't seen anyone report issues with using the mainline driver, closing.

**Comment by ianblenke** [comment]
@marineam, I think there may be a miscommunication here. It isn't that it doesn't work, it's that it works sub-optimally, not using the SR-IOV capabilities available to it were the driver capable of doing so.

When I run this command:

    aws ec2 describe-instance-attribute --instance-id i-98fc9c62 --attribute sriovNetSupport

The output is:

    {
        "InstanceId": "i-98fc9c62",
        "SriovNetSupport": {}
    }

If I run this against an amazon linux image from an ElasticBeanstalk deploy, I see:

    {
        "InstanceId": "i-3d2287d4",
        "SriovNetSupport": {
            "Value": "simple"
        }
    }

This means that the CoreOS AMI is not using a network driver that is compatible with SR-IOV.

The guide mentioned in my original report for this issue describes this in some minor detail:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

You may wish to re-open this issue and take a look at the driver version that is being used.

**Comment by marineam** [comment]
@ianblenke Setting the attribute on the AMI isn't related to the version bump requested in this bug. The latest alphas now have the attribute:

```
$ ec2-describe-image-attribute --sriov ami-ff35fc94
sriovNetSupport	ami-ff35fc94		simple
```

Was fixed in https://github.com/coreos/scripts/pull/417 https://coreos.com/releases/#735.0.0

On a different note, my intent was to only enable it on 735 but looks like the flag got enabled for the current beta and stable AMIs as well. Hopefully that hasn't caused a problem for anyone :(
