### ISSUE TITLE
Please update open-vm-tools to 9.10.0

### ISSUE THREAD

**Issue by oliverkurth** [coreos/coreos-overlay#1151]
A new version of open-vm-tools has been released and is available on github: https://github.com/vmware/open-vm-tools/tree/stable-9.10.x
the release tag is:
https://github.com/vmware/open-vm-tools/releases/tag/stable-9.10.0
This corresponds with the newly released vsphere 6.0. It includes deploypkg. It also includes the new components vgauth and rabbitmq, which add new dependencies, but these new components can be disabled with the configure script.

**Comment by marineam** [comment]
What are these new dependencies? What is lost if we don't enable the new components that need them?

**Comment by AntonioMeireles** [comment]
@marineam -  the rationale to bump is that if you don't connection with later vCenter revs is tricky, at best.
 
regarding the new features...
- **deploypkg** is handy as if you want to use VMware Site Recovery Manager backup tools, you just need the plugin in the guest If you plan on (for  duplicating the machine, using it as a master image). not completly sold missing it is a deal-breaker given CoreOS' use case :smile:  
- **vgauth** is about automated guest auth.
- the **rabbitmq** (proxy) is for plugging into vFabric's machinery...  
  World survived without this features so far, so as a first step, IMnsHO i guess that the *thing* can be reasonably bumped with those disabled (and by doing that one should not, at sight, get any dep changes relative to the ones now).  

Long term, and assuming that CoreOS cares about the enterprise *whatever that is*, where like it or not, VMware has an entrenched place, it *could* make sense to enable them...
