### ISSUE TITLE
Enable dcdbas and dell_rbu kernel drivers

### ISSUE THREAD

**Issue by zapient** [coreos/coreos-overlay#1155]
Please enable the Dell Systems Management Base and Dell Remote BIOS Update kernel drivers since they are in the mainline kernel.

> The dcdbas and dell_rbu drivers are Linux kernel drivers that are required to perform certain operations in libsmbios. For example, BIOS updates require the dell_rbu driver. These kernel drivers are included in the standard linux kernel starting with Linux 2.6.14. If you have this kernel and these drivers are not present, please talk to your vendor about enabling these drivers.

**Comment by marineam** [comment]
Resolved in https://github.com/coreos/bugs/issues/346
