### ISSUE TITLE
include actool and docker2aci binaries to CoreOS

### ISSUE THREAD

**Issue by jonboulle** [coreos/coreos-overlay#1209]
_From @rimusz on April 19, 2015 10:39_

 actool and docker2aci binaries should be included to CoreOS as rkt docs have many references to them, 
which brings a confusion when you try to use them and they are not found

_Copied from original issue: coreos/rkt#788_

**Comment by jonboulle** [comment]
I am a bit ambivalent about this, might be better to just streamline the docs or make them easier to retrieve (simple wrapper script?)

@marineam @crawford thoughts?

**Comment by mischief** [comment]
actool is in the image with #1224. it was decided docker2aci won't be in the image since rkt is using it internally.

**Comment by rimusz** [comment]
@mischief 
I still do not understand why docker2aci binary cannot be included in CoreOS image?
That would make much easier to convert and save docker images as rkt does not allow to save them.
