### ISSUE TITLE
Git/OpenSSL doesn't handle some valid certs

### ISSUE THREAD

**Issue by ndarilek** [coreos/coreos-overlay#1256]
Not sure if this is the correct repo for this report, if not then I'll file it elsewhere. The version of Git shipped with CoreOS stable fails to check out some Git repositories over SSL. This can complicate matters if your deployment process involves pulling new code into an instance. For instance, see this (this isn't the repo I'm trying to pull into production but it demonstrates the issue):

core@core-01 ~ $ git clone https://dev.thewordnerd.info/git/spiel/spiel
Cloning into 'spiel'...
fatal: unable to access 'https://dev.thewordnerd.info/git/spiel/spiel/': error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
core@core-01 ~ $ GIT_SSL_NO_VERIFY=1 git clone https://dev.thewordnerd.info/gi>
Cloning into 'spiel'...
fatal: unable to access 'https://dev.thewordnerd.info/git/spiel/spiel/': error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

My repositories are behind Cloudflare's free SSL certificates. When I had this issue under Windows, the key was upgrading Git to version 2.3. Various searches seemed to indicate that an OpenSSL update might also help. The problem also seems to be gone on modern versions of Ubuntu and Fedora--at least, so it does based on my Docker tests.

Thanks.

**Comment by glevand** [comment]
Hi,

Both git and openssl are in the portage-stable repos.  openssl was just updated: https://github.com/coreos/portage-stable/pull/195.  I submitted a pull request for git.

Hope it helps.

-Geoff

**Comment by ndarilek** [comment]
Excellent, thanks. Is that the repository where I should file bugs
against outdated CoreOS packages in the future? Wasn't sure where this
should have gone.

**Comment by glevand** [comment]
Some packages are in portage-stable, some are in coreos-overlay.  You can find out with with something like this:

  $ equery m dev-vcs/git
   * dev-vcs/git [portage-stable]

coreos-overlay has some missing metadata, so you''l get an error 'Package xxx is missing metadata.xml' for those packages.  I've already pointed this problem out to the CoreOS guys, and I think we will try to add metadata from now on.

-Geoff

**Comment by crawford** [comment]
On 05/14, Nolan Darilek wrote:
> Excellent, thanks. Is that the repository where I should file bugs
> against outdated CoreOS packages in the future? Wasn't sure where this
> should have gone.

You can always file bugs under github.com/coreos/bugs and we will triage
them for you.

-Alex

**Comment by marineam** [comment]
Closing since https://github.com/coreos/portage-stable/issues/196 was merged some time ago.
