### ISSUE TITLE
Upgrade systemd to v220

### ISSUE THREAD

**Issue by alban** [coreos/coreos-overlay#1264]
I would like to have [systemd v220](http://lists.freedesktop.org/archives/systemd-devel/2015-May/032147.html) in CoreOS.

It will also be useful for rkt: rkt can be built using the CoreOS image. This will unblock https://github.com/coreos/rkt/issues/845.

The previous systemd upgrade to v219 was https://github.com/coreos/coreos-overlay/pull/1186

**Comment by jonboulle** [comment]
Fixed by #1272
