### ISSUE TITLE
Add static docker binary for in-container use cases

### ISSUE THREAD

**Issue by cap10morgan** [coreos/coreos-overlay#1273]
There is a common pattern of bind-mounting `/var/run/docker.sock` in containers that need to query and/or manipulate the host's Docker daemon. However, you often need the docker client binary in these containers too. In order to keep that client binary's version in sync with the daemon, people often just bind-mount the host's `/usr/bin/docker` into the container. But this is tricky on CoreOS because `/usr/bin/docker` is a dynamically-linked binary.

The other alternative–installing a specific version of Docker in the image–is dangerous because CoreOS can update the Docker daemon's version at any time and reboot on to it. This will break any containers trying to use the host's `/var/run/docker.sock` with an image-baked-in docker binary if the API version changes (which it often does).

A better alternative would be for CoreOS to do one of these 2 things:

1. Statically link `/usr/bin/docker` so it can be easily bind-mounted into containers.
1. Provide a separate, statically-linked, client-only docker binary somewhere else that can be bind-mounted into containers and is kept in version-sync with the Docker daemon.

**Comment by marineam** [comment]
Static binaries introduce their own sets of problems and in general it is only practical for us to support binaries/libraries shipped in the base CoreOS image while inside the base CoreOS environment. I don't have a good recommendation beyond maintaining the container that needs docker with an up-to-date copy of docker.

**Comment by cap10morgan** [comment]
@marineam This is utterly irreconcilable with CoreOS' recommendation to allow auto-updates and reboots onto new Docker versions. Surely there must be more to do here?

**Comment by marineam** [comment]
@cap10morgan honestly, I hadn't realized that Docker refuses to provide a stable or backwards compatible API which I presume is the reason for needing this in the first place.

Perhaps some job at startup to grab the right version of a static docker before starting containers? The docker build inside of CoreOS cannot be static (at least for now) because static Go binaries don't use libc for host name resolution and we currently depend on the libc behavior. That may change in the future.

**Comment by cap10morgan** [comment]
@marineam Yes, it's unfortunate. But thanks, that's a good suggestion. I'll probably try to throw that together soon.

**Comment by marineam** [comment]
If that scheme works perhaps an example script/config would be worth adding to our documentation :)

**Comment by sigma** [comment]
:+1: on that issue :(

@marineam out of curiosity, what exactly do you rely on for hostname resolution? Presumably a separate docker.static binary, even with a slightly different behavior in this regard, should not affect the behavior of the rest of the stack: only the people who'd actually use it to implement docker-in-docker could be affected (personally I don't think I'd mind it nearly as much as the current broken behavior).

Also, I think there's some work in this area for Go 1.5? Any chance of revisiting that issue once it's released, if whatever you rely on is fixed?

And yes, the fact that there's no notion of compatibility whatsoever in Docker API is a gigantic PITA...

**Comment by sigma** [comment]
for the record, an almost-not-tested-at-all attempt at keeping a /opt/bin/docker.static binary in sync with whatever is in the image currently (well, at each boot, but that's why immutable infra is great :))
https://gist.github.com/sigma/077606735bb738a73fb2

Example of use:

```
core@localhost ~ $ docker --version
Docker version 1.5.0, build a8a31ef-dirty
core@localhost ~ $ docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /opt/bin/docker.static:/usr/bin/docker alpine:latest /usr/bin/docker --version
Docker version 1.5.0, build a8a31ef
core@localhost ~ $
```
