### ISSUE TITLE
tzdata in stable

### ISSUE THREAD

**Issue by dmitryint** [coreos/coreos-overlay#1275]
Please, update timezone data in stable branch

**Comment by crawford** [comment]
Updates start off in Alpha and work their way to Stable. It's uncommon to backport a change and is typically reserved for security vulnerabilities.

If you need the update now, I'd suggest grabbing an image from the alpha or beta channels.

**Comment by dmitryint** [comment]
In many, if not all, distributions of different OS, update time zone data are considered critical. I think this is a case where the update needs backporting immediately in all branches, and not go all the way from alpha to stable.

**Comment by crawford** [comment]
@dmitryint this fix is now in 681.0.0 (current Stable).
