### ISSUE TITLE
Include tools to set filesystem ACL

### ISSUE THREAD

**Issue by wikiwi** [coreos/coreos-overlay#1555]
I can't find the tools `setfacl` and `getfacl` to manage the filesystem acl. 
I am mounting `var/log/journal` on a different device and cannot set the correct acl requirements for `systemd-journal`.

Is it possible to include the acl tools?

**Comment by mischief** [comment]
can you run setfacl and getfacl from a container?

**Comment by wikiwi** [comment]
Thanks, that works! I'll workaround using the toolbox.
