### ISSUE TITLE
running pypy missing librarys

### ISSUE THREAD

**Issue by f0** [coreos/coreos-overlay#438]
Hi,

i ship pypy with the oem partition, bit i van not run because of library errors:

```
core@core-cl-id-01 ~ $ ldd /opt/pypy/bin/pypy
/opt/pypy/bin/pypy: /usr/lib64/libssl.so.1.0.0: no version information available (required by /opt/pypy/bin/pypy)
/opt/pypy/bin/pypy: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by /opt/pypy/bin/pypy)
	linux-vdso.so.1 (0x00007fffcfee6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff84db04000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff84d806000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff84d5ef000)
	libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007ff84d382000)
	libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007ff84cfa1000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff84cd99000)
	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007ff84cb6b000)
	libbz2.so.1.0 => /lib64/libbz2.so.1.0 (0x00007ff84c95b000)
	libffi.so.6 => /usr/lib64/libffi.so.6 (0x00007ff84c752000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ff84c51b000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007ff84c318000)
	libtinfo.so.5 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff84c0fb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff84bd4e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff84dd08000)
'''



regards f0

**Comment by lamielle** [comment]
Was this fixed in a recent CoreOS release @f0?  I was seeing this too and will check today of the error is still present for me.

**Comment by f0** [comment]
@lamielle  don't know if its fixed, but  its an old bug and it seems that nobody cares about this....

**Comment by crawford** [comment]
If you need python and pypy, we suggest distributing that within a container. The OS does not ship some of the libraries you are missing.

**Comment by lamielle** [comment]
Hi @crawford: the article [here](https://coreos.com/blog/managing-coreos-with-ansible/) implies that running Python directly on the CoreOS host is the 'recommended' way for using Ansible with CoreOS.  If the referenced Ansible bootstrap module isn't the best way to go, any chance someone from the CoreOS team could put together a followup?  I've been using this approach successfully myself, but do see this library error.

**Comment by kelseyhightower** [comment]
@f0 @lamielle I think we should be able to build a "static" python or pypy kinda like what's going on here: http://phusion.github.io/traveling-ruby

**Comment by lamielle** [comment]
@kelseyhightower Yes, it would be nice to have a Python equivalent of that 'ruby in a box' package.  I do think it is a bit ironic that Travelling Ruby is basically a container.  : )

**Comment by v3ss0n** [comment]
There is portable-pypy and relocateable python , existed for very long.
https://github.com/squeaky-pl/portable-pypy
https://github.com/Infinidat/relocatable-python
