### ISSUE TITLE
how to ensure the compatibility between os of docker container and coreos kernel

### ISSUE THREAD

**Issue by wangbicheng** [coreos/coreos-overlay#773]
There is a situation that we have lots of applications based on SLES. We are planning to migrate them to CoreOS. The question is that how to ensure the compatibility between SLES of docker container and CoreOS kernel? Thank you!

**Comment by lamielle** [comment]
Hi @kelseyhightower, it seems this issue has been open for quite sometime.  Given your previous comment it's probably find to close it out now.

(I am just reading through open CoreOS tickets and trying to contribute where I can.)
