### ISSUE TITLE
/usr/share/oem/lib64 should be in /etc/ld.so.conf

### ISSUE THREAD

**Issue by oliverkurth** [coreos/coreos-overlay#937]
I am adding libraries to the oem partition. In order for the dynamic linker to find them, the directory /usr/share/oem/lib64 needs to be added to the search path. This needs to be done when the image is built (not at run time), because otherwise the check for dependencies when doing build_packages will fail.

What's a good place to add a file to /etc/ld.so.conf.d/ ?

**Comment by marineam** [comment]
This was handled in a different ticket a while ago, `oem/lib64` is now in ld.so.conf *and* vmtoolsd is compiled with rpath so we are double-covered.
